// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClu2fQnvK2eXIHG1UjOFnEMoiC6bA-RCI',
    appId: '1:497468651729:web:a79d16284d36d3cac0adf0',
    messagingSenderId: '497468651729',
    projectId: 'mad-cw6-ca278',
    authDomain: 'mad-cw6-ca278.firebaseapp.com',
    storageBucket: 'mad-cw6-ca278.firebasestorage.app',
    measurementId: 'G-E5KZ2V35WE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnxFCdwtJNWc9Im2hMOpVDqVhR314v298',
    appId: '1:497468651729:android:48fc896395d14f97c0adf0',
    messagingSenderId: '497468651729',
    projectId: 'mad-cw6-ca278',
    storageBucket: 'mad-cw6-ca278.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZy3ApzwMY-wD2f-g_dk7dTDUMVbHMr14',
    appId: '1:497468651729:ios:f6ec72a7699b2357c0adf0',
    messagingSenderId: '497468651729',
    projectId: 'mad-cw6-ca278',
    storageBucket: 'mad-cw6-ca278.firebasestorage.app',
    iosBundleId: 'com.example.cw6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZy3ApzwMY-wD2f-g_dk7dTDUMVbHMr14',
    appId: '1:497468651729:ios:f6ec72a7699b2357c0adf0',
    messagingSenderId: '497468651729',
    projectId: 'mad-cw6-ca278',
    storageBucket: 'mad-cw6-ca278.firebasestorage.app',
    iosBundleId: 'com.example.cw6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClu2fQnvK2eXIHG1UjOFnEMoiC6bA-RCI',
    appId: '1:497468651729:web:2f5b7460d7846416c0adf0',
    messagingSenderId: '497468651729',
    projectId: 'mad-cw6-ca278',
    authDomain: 'mad-cw6-ca278.firebaseapp.com',
    storageBucket: 'mad-cw6-ca278.firebasestorage.app',
    measurementId: 'G-5P6WSNJMW2',
  );
}
